spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://yourdomain.com}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  packages-to-scan: com.example.devflow.controller
